"""Fixed editied field in messages

Revision ID: 5bbeee1877f8
Revises: 18e69f100c38
Create Date: 2022-11-16 05:11:21.625668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5bbeee1877f8'
down_revision = '18e69f100c38'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'edited',
               existing_type=sa.DateTime(),
               nullable=True,
               existing_server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'edited',
                    existing_type=sa.DateTime(),
                    nullable=True,
                    existing_server_default=text("CURRENT_TIMESTAMP"))
    # ### end Alembic commands ###
