version: '3'
services:
  rmq:
    image: rabbitmq:3.11.3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user

  redis:
    image: redis:7.0.5-alpine
  db:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: clean-chat
    volumes:
      - ./clean-chat-back/.db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#  flower:
#    image: clean-chat_back
#    command: celery flower -A main.celery --address=0.0.0.0 --port=5555
#    volumes:
#      - ./clean-chat-back/:/code
#    env_file:
#      - ./clean-chat-back/.env
#    ports:
#      - "5555:5555"
#    depends_on:
#      - back
#      - redis
#      - rmq
#  ml:
#    image: clean-chat_back
#    command: celery -A main.celery worker --loglevel=info
#    volumes:
#      - ./clean-chat-back/:/code
#    env_file:
#      - ./clean-chat-back/.env
#    depends_on:
#      - back
#      - redis
#      - rmq
  back:
    build: ./clean-chat-back/
    command: './dev-run.sh'
    volumes:
      - ./clean-chat-back/:/code
    env_file:
      - ./clean-chat-back/.env
    ports:
      - "5555:5555"
      - "8000:8000"
    depends_on:
      - db
      - redis
      - rmq
  front:
    build: ./clean-chat-front/
    command: 'npm run dev-docker'
    volumes:
      - ./clean-chat-front/:/code
    ports:
      - "5173:5173"
    env_file:
      - ./clean-chat-front/.env
    depends_on:
      - back
