version: '3'
services:
  rmq:
    image: rabbitmq:3.11.3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: user

  redis:
    image: redis:7.0.5-alpine
  db:
    image: postgres:14.6-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: clean-chat
    volumes:
      - ./.db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build: .
    command: './dev-run.sh'
    volumes:
      - ./:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

